// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebPharmacy.Data;

#nullable disable

namespace WebPharmacy.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebPharmacy.Models.LoaiThuoc", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("TenLoai")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("LoaiThuocs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            TenLoai = "Thuốc kháng sinh"
                        },
                        new
                        {
                            Id = 2,
                            TenLoai = "Thuốc giảm đau"
                        },
                        new
                        {
                            Id = 3,
                            TenLoai = "Vitamin và Khoáng chất"
                        });
                });

            modelBuilder.Entity("WebPharmacy.Models.Thuoc", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Gia")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("HinhAnhUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LoaiThuocId")
                        .HasColumnType("int");

                    b.Property<string>("MoTa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenThuoc")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("LoaiThuocId");

                    b.ToTable("Thuocs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Gia = 150000m,
                            HinhAnhUrl = "https://placehold.co/500x500/28a745/white?text=Amoxicillin",
                            LoaiThuocId = 1,
                            MoTa = "Thuốc kháng sinh điều trị nhiễm khuẩn do vi khuẩn nhạy cảm gây ra.",
                            TenThuoc = "Amoxicillin 500mg"
                        },
                        new
                        {
                            Id = 2,
                            Gia = 50000m,
                            HinhAnhUrl = "https://placehold.co/500x500/28a745/white?text=Paracetamol",
                            LoaiThuocId = 2,
                            MoTa = "Thuốc giảm đau, hạ sốt hiệu quả và an toàn.",
                            TenThuoc = "Paracetamol 500mg"
                        },
                        new
                        {
                            Id = 3,
                            Gia = 95000m,
                            HinhAnhUrl = "https://placehold.co/500x500/28a745/white?text=Vitamin+C",
                            LoaiThuocId = 3,
                            MoTa = "Bổ sung Vitamin C, tăng cường hệ miễn dịch cho cơ thể.",
                            TenThuoc = "Vitamin C 1000mg"
                        },
                        new
                        {
                            Id = 4,
                            Gia = 75000m,
                            HinhAnhUrl = "https://placehold.co/500x500/28a745/white?text=Ibuprofen",
                            LoaiThuocId = 2,
                            MoTa = "Thuốc chống viêm không steroid, giảm đau, hạ sốt và chống viêm.",
                            TenThuoc = "Ibuprofen 400mg"
                        });
                });

            modelBuilder.Entity("WebPharmacy.Models.Thuoc", b =>
                {
                    b.HasOne("WebPharmacy.Models.LoaiThuoc", "LoaiThuoc")
                        .WithMany("Thuocs")
                        .HasForeignKey("LoaiThuocId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LoaiThuoc");
                });

            modelBuilder.Entity("WebPharmacy.Models.LoaiThuoc", b =>
                {
                    b.Navigation("Thuocs");
                });
#pragma warning restore 612, 618
        }
    }
}
